# Generated by Django 4.2.10 on 2024-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='items',
            constraint=models.CheckConstraint(check=models.Q(('countInStock__gte', 0)), name='nonNegativeCountInStock'),
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.CheckConstraint(check=models.Q(('availableStock__gte', 0)), name='nonNegativeAvailableStock'),
        ),
    ]
