# Generated by Django 4.2.10 on 2024-02-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_items_nonnegativecountinstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('itemName', models.CharField(max_length=64)),
                ('availableStock', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('IN_STOCK', 'IN_STOCK')], default='IN_STOCK', max_length=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='uniqueSKU&Tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sku',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='Items.tag'),
        ),
    ]
