# Generated by Django 4.2.10 on 2024-02-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_remove_items_category_remove_tag_uniquesku_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
    ]
