# Generated by Django 4.2.10 on 2024-02-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_rename_categoryname_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
